vector_version: 0.38.0
vector_config_dir: "/opt/vector_config"
vector_config:
  sources:
    fake_log:
      type: demo_logs
      format: syslog
      interval: 3
      decoding:
        codec: syslog
  sinks:
    sink_id:
      type: clickhouse
      inputs:
        - fake_log
      endpoint: "http://{{ hostvars['clickhouse-vm']['ansible_host'] }}:8123"
      database: log
      table: syslog
      compression: gzip
      skip_unknown_fields: true
